default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash jq
  interruptible: true

stages:
  - build

build-images:
  stage: build
  script:
    - scripts/build_images.sh
  except:
    refs:
      - master

build-images-and-push:
  stage: build
  script:
    - scripts/build_images.sh
    - scripts/push_images.sh
  only:
    refs:
      - master
