apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  KC_DB_URL_HOST: 'postgres-16'
  KC_DB_URL_PORT: '5432'
  KC_DB_URL_DATABASE: 'keycloak'
  KC_HOSTNAME: 'auth.bts-crew.com'
  KC_PROXY_HEADERS: 'xforwarded'
  KC_HTTP_ENABLED: 'true'
  KC_LOG: 'console'
  KC_LOG_CONSOLE_FORMAT: 'ts="%d{yyyy-MM-dd HH:mm:ss.SSS}" level=%p thread=%t-%t{id} msg="%s" %e%n'
  JAVA_OPTS_KC_HEAP: '-XX:MaxRAMPercentage=80 -XX:+ExitOnOutOfMemoryError -XX:+UseG1GC'
