apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: auth.bts-crew.com
    external-dns.alpha.kubernetes.io/target: k8s-traefik-public-cc63ae0f3b4f5869.elb.eu-west-1.amazonaws.com
spec:
  type: ClusterIP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  secretName: {{ include "keycloak.fullname" . }}-tls
  dnsNames:
    - auth.bts-crew.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "keycloak.fullname" . }}-http
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`auth.bts-crew.com`)
      middlewares:
        - name: redirect-http-to-https
      services:
        - kind: TraefikService
          name: noop@internal
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "keycloak.fullname" . }}-https
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.bts-crew.com`) && PathPrefix(`/realms/{realm:.*}/metrics`)
      middlewares:
        - name: ip-allowlist-internal
      services:
        - kind: Service
          name: {{ include "keycloak.fullname" . }}
          port: 8080
    - kind: Rule
      match: Host(`auth.bts-crew.com`) && PathPrefix(`/`)
      middlewares:
        - name: rate-limit
      services:
        - kind: Service
          name: {{ include "keycloak.fullname" . }}
          port: 8080
  tls:
    secretName: {{ include "keycloak.fullname" . }}-tls
