apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-http-to-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: auth.bts-crew.com
      http:
        paths:
          - backend:
              service:
                name: {{ include "keycloak.fullname" . }}
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - auth.bts-crew.com
      secretName: {{ include "keycloak.fullname" . }}-tls
