apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  refreshInterval: 15m
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: /backstage/keycloak/admin-credentials
        property: username
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: /backstage/keycloak/admin-credentials
        property: password
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: /backstage/keycloak/db-credentials
        property: username
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: /backstage/keycloak/db-credentials
        property: password
