name: Set up
description: Installs terraform and sets up AWS

inputs:
  realm:
    description: ''
    required: true
  aws-role-arn:
    description: The ARN of the AWS role to authenticate with
    required: true
  ssh-private-key:
    description: The private SSH key used to download the terraform modules
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: terraform/realms/${{ inputs.realm }}
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        bash <(curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh) -b $HOME/.local/bin
        tfswitch -b $HOME/.local/bin/terraform
    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Configure AWS credentials
      uses: mcblair/configure-aws-profile-action@v0.1.1
      with:
        profile-name: backstage
        role-arn: ${{ inputs.aws-role-arn }}
        region: eu-west-1
