name: Apply Realms

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/realms-apply.yml'
      - 'terraform/**/*'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  detect-pr-number:
    name: Detect PR number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-pr-number
        name: Determine PR number
        env:
          COMMIT_SHA: ${{ github.event.after }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/detect-pr-number.sh
    outputs:
      pr-number: ${{ steps.set-pr-number.outputs.pr_number }}

  realm-matrix:
    name: Realm matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-matrix
        name: Determine realm matrix
        env:
          BASE_SHA: ${{ github.event.before }}
          HEAD_SHA: ${{ github.event.after }}
        run: scripts/detect-changed-realms.sh
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  apply:
    name: Apply realm
    runs-on: ubuntu-latest
    needs:
      - detect-pr-number
      - realm-matrix
    if: ${{ needs.config-matrix.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        realm: ${{ fromJSON(needs.realm-matrix.outputs.matrix) }}
    defaults:
      run:
        shell: bash
        working-directory: terraform/realms/${{ matrix.realm }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-terraform
        with:
          realm: ${{ matrix.realm }}
          aws-role-arn: ${{ vars.AWS_APPLY_ROLE_ARN }}
          ssh-private-key: ${{ secrets.TF_MODULES_PRIVATE_SSH_KEY }}
      - name: init
        id: init
        run: terraform init -no-color 2>&1 | tee /tmp/${{ github.run_id }}.init.txt
      - name: fmt check
        id: fmt-check
        run: terraform fmt -check -recursive -no-color 2>&1 | tee /tmp/${{ github.run_id }}.fmt-check.txt
      - name: validate
        id: validate
        run: terraform validate -no-color 2>&1 | tee /tmp/${{ github.run_id }}.validate.txt
      - name: apply
        id: apply
        run: |
          aws s3 cp \
            s3://backstage-terraform-plan-outputs/${{ github.repository }}/${{ needs.detect-pr-number.outputs.pr-number }}/${{ matrix.realm }}.out \
            plan.out \
            --profile backstage
          terraform apply -no-color plan.out 2>&1 | tee /tmp/${{ github.run_id }}.apply.txt
      - name: cleanup
        if: ${{ always() }}
        run: |
          aws s3 rm \
            s3://backstage-terraform-plan-outputs/${{ github.repository }}/${{ needs.detect-pr-number.outputs.pr-number }}/${{ matrix.realm }}.out \
            --profile backstage
      - name: build comment
        if: ${{ always() }}
        id: build-comment
        uses: actions/github-script@v7
        env:
          STEP_INIT_OUTCOME: ${{ steps.init.outcome }}
          STEP_FMT_CHECK_OUTCOME: ${{ steps.fmt-check.outcome }}
          STEP_VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
          STEP_APPLY_OUTCOME: ${{ steps.apply.outcome }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { buildComment } = require('./scripts/actions-helpers.js');
            
            return buildComment({
              context,
              core,
              command: 'apply',
              configName: '${{ matrix.realm }}',
              steps: [
                { name: 'init' },
                { name: 'fmt-check' },
                { name: 'validate' },
                { name: 'apply' },
              ]
            });
      - name: post comment
        if: ${{ always() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ${{ steps.build-comment.outputs.result }}
          comment_tag: ${{ matrix.realm }}
          pr_number: ${{ needs.detect-pr-number.outputs.pr-number }}
          mode: upsert
